dictionaries = ["en_gb"]
words = [
    "alphanumerics",
    "analyzer",
    "ansible",
    "ansiblels",
    "antosha",
    "asdtgmnel",
    "asmfmt",
    "augroup",
    "autoindent",
    "autopairs",
    "autoread",
    "autosession",
    "autotag",
    "bashls",
    "bibtex",
    "bufnr",
    "cmake",
    "cmakelint",
    "codelldb",
    "colorcolumn",
    "commentstring",
    "completeopt",
    "cssls",
    "cursorline",
    "cwd",
    "dap",
    "decremental",
    "dockerls",
    "evdev",
    "expandtab",
    "fileencoding",
    "fileformat",
    "folke",
    "fzf",
    "ghci",
    "ghcups",
    "gitcommit",
    "githook",
    "gitsigns",
    "glyphs",
    "gmc",
    "gomod",
    "gopls",
    "gosum",
    "hls",
    "hlsearch",
    "hoogle",
    "hrsh",
    "ignorecase",
    "incsearch",
    "integrations",
    "isort",
    "jglasovic",
    "josean",
    "jsonlint",
    "jsonls",
    "jsregexp",
    "kdheepak",
    "keybinds",
    "keycap",
    "keymap",
    "keymaps",
    "keypress",
    "linters",
    "lspconfig",
    "lspkind",
    "luadoc",
    "lualine",
    "luasnip",
    "makefiles",
    "mapleader",
    "markdownlint",
    "maximizer",
    "maxwidth",
    "menuone",
    "mfussenegger",
    "mkdocs",
    "monokai",
    "neovim",
    "netrw",
    "nginx",
    "nixd",
    "nixfmt",
    "nixos",
    "noselect",
    "nvim",
    "oldfiles",
    "openssl",
    "parsers",
    "pydocstyle",
    "pyproject",
    "pyright",
    "qwfrbyuiop",
    "rstcheck",
    "scrolloff",
    "shiftwidth",
    "signcolumn",
    "smartcase",
    "softtabstop",
    "splitbelow",
    "splitright",
    "stylelua",
    "stylua",
    "systemdlint",
    "tabclose",
    "tabn",
    "tabnew",
    "tabp",
    "tabstop",
    "tarmak",
    "termguicolors",
    "terraformls",
    "timeoutlen",
    "tlsv",
    "tmux",
    "tui",
    "unnamedplus",
    "venv",
    "vimdoc",
    "vscode",
    "xdg",
    "yamllint",
    "yamlls",
    "zxcvbkh",
]
ignore_paths = [
    ".git/**/*",
    "pyproject.toml",
]
ignore_patterns = ['\b[A-Z]{2,}\b']
use_global = false
